DROP TABLE IF EXISTS PAYMENT_DATA;
DROP TABLE IF EXISTS ACCOUNT_DATA;
DROP TABLE IF EXISTS PAYMENT_SUMMARY;

CREATE TABLE PAYMENT_DATA
(
    PAYMENT_ID    BIGINT PRIMARY KEY,
    ACCOUNT_ID    BIGINT,
    AMOUNT        INT,
    METHOD_TYPE   VARCHAR(2),
    ITEM_CATEGORY VARCHAR(3),
    REGION        VARCHAR(2)
);

CREATE TABLE ACCOUNT_DATA
(
    ACCOUNT_ID BIGINT PRIMARY KEY,
    RESIDENCE  VARCHAR(2),
    AGE        INT
);

CREATE TABLE PAYMENT_SUMMARY
(
    GROUP_ID     VARCHAR(7) PRIMARY KEY,
    COUNT        BIGINT,
    TOTAL_AMOUNT BIGINT,
    AVG_AMOUNT   INT,
    MIN_AMOUNT   INT,
    MAX_AMOUNT   INT,
    CREATED_TIME TIMESTAMP
);

ALTER TABLE PAYMENT_DATA
    ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT_DATA (ACCOUNT_ID);
